export const slides = [
  {
    startDate: 1980,
    endDate: 1986,
    events: [
      { year: 1980, description: 'Выборы Рональда Рейгана, США' },
      { year: 1981, description: 'Попытка убийства Рональда Рейгана, США' },
      { year: 1982, description: 'Бегство Пиночета от обвинений в Чили' },
      { year: 1983, description: 'Начало конфликта в Гренаде, США и Канада вмешались' },
      { year: 1984, description: 'Повторное избрание Рональда Рейгана, США' },
      { year: 1985, description: 'Михаил Горбачёв становится Генеральным секретарём КПСС, СССР' },
      { year: 1986, description: 'Взрыв Чернобыльской АЭС и политические последствия, СССР' },
    ],
    category: 'Политика',      
  },
  {
    startDate: 1987,
    endDate: 1991,
    events: [
      { year: 1987, description: '"Predator" / Хищник, США (John McTiernan)' },
      { year: 1988, description: '"Who Framed Roger Rabbit" / Кто подставил кролика Роджера, США (Robert Zemeckis)' },
      { year: 1989, description: '"Back to the Future Part II" / Назад в будущее 2, США (Robert Zemeckis)' },
      { year: 1990, description: '"Die Hard 2" / Крепкий орешек 2, США (Renny Harlin)' },
      { year: 1991, description: '"The Silence of the Lambs" / Молчание ягнят, США (Jonathan Demme)' },       
    ],
    category: 'Кино',
  },
  {
    startDate: 1992,
    endDate: 1997,
    events: [
      { year: 1992, description: 'Нобелевская премия по литературе - Дерек Уолкотт, "За блестящий образец карибского эпоса в 64 разделах' },
      { year: 1994, description: '"Бессоница" - роман Стивена Кинга' },
      { year: 1995, description: 'Нобелевская премия по литературе - Шеймас Хини' },
      { year: 1997, description: '«Гарри Поттер и Тайная комната»' },
    ],
    category: 'Литература',
  },
  {
    startDate: 1999,
    endDate: 2004,
    events: [
      { year: 1999, description: 'Премьера балета "Золушка" (Жан-Кристоф Майо), Опера Монте-Карло, Монако' },
      { year: 2000, description: 'Возобновлено издание журнала "Театр", Россия' },
      { year: 2002, description: 'Премьера трилогии "Берег Утопии" Тома Стоппарда, Королевский Национальный театр, Лондон, Великобритания' },
      { year: 2003, description: 'Премьера "Короля Лира" с Иэном Маккелленом, Глобус-театр, Лондон, Великобритания' },
      { year: 2004, description: 'Открытие Театра наций в Москве, Россия' },
    ],      
    category: 'Театр',
  },
  {
    startDate: 2005,
    endDate: 2014,
    events: [
      { year: 2005, description: 'Финал Лиги чемпионов: Ливерпуль победил Милан, футбольная Европа' },
      { year: 2006, description: 'Чемпионат мира по футболу: Италия выиграла у Франции, Германия' },
      { year: 2008, description: 'Летние Олимпийские игры: Пекин, Китай' },
      { year: 2009, description: 'Формула-1: Дж. Баррикелло уходит из Ferrari, чемпионат мира выиграл Дж. Баттон' },
      { year: 2011, description: 'Чемпионат мира по хоккею: Россия выиграла у Канады' },
      { year: 2012, description: 'Летние Олимпийские игры: Лондон, Великобритания' },
      { year: 2013, description: 'Серена Уильямс выиграла Уимблдон, теннис' },
      { year: 2014, description: 'Чемпионат мира по футболу: Германия победила Аргентину, Бразилия' },
    ],
    category: 'Спорт',      
  },
  {
    startDate: 2015,
    endDate: 2022,
    events: [
      { year: 2015, description: 'Обнаружение воды на Марсе, NASA, США' },
      { year: 2016, description: 'Открытие гравитационных волн, LIGO, США' },
      { year: 2017, description: 'Первая фотография черной дыры, Event Horizon Telescope, международный' },
      { year: 2018, description: 'Запуск миссии Parker Solar Probe к Солнцу, NASA, США' },
      { year: 2019, description: 'Объявление первого изображения черной дыры, EHT Collaboration, международный' },
      { year: 2020, description: 'Разработка первых вакцин против COVID-19, Pfizer/BioNTech, Moderna' },
      { year: 2021, description: 'Телескоп James Webb успешно выведен на орбиту, NASA/ESA/CSA' },
      { year: 2022, description: 'Прорыв в области термоядерного синтеза, National Ignition Facility, США' },
    ],
    category: 'Наука',      
  },
]